---
  - name: Install Nginx on Ubuntu
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: install nginx on CentOS
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "CentOS"

  - name: Install Jenkins keyring on Ubuntu
    shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    when: ansible_os_family == "Debian"

  - name: Install Jenkins repository on Ubuntu
    shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    when: ansible_os_family == "Debian"

  - name: Install openjdk on ubuntu
    apt:
      name: openjdk-11-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: Install jdk on centos
    yum:
      name: openjdk-11-jdk
      state: present
    when: ansible_os_family == "CentOS"

  - name: Update apt package cache on ubuntu
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: update packages cache on centos
    yum:
      update_cache: yes
    when: ansible_os_family == "CentOS"

  - name: install jenkins on ubuntu
    apt:
      name: jenkins
      state: present
    when: ansible_os_family == "Debian"
    notify: Restart Nginx

  - name: Install jenkins on CentOS
    yum:
      name: jenkins
      state: present
    when: ansible_os_family == "CentOS"

  - name: Enable Nginx and Jenkins services
    service:
      name: "{{ item }}"
      enabled: true
      state: started
    loop:
      - nginx
      - jenkins
  - name: Create Nginx configuration file for Jenkins
    file:
      path: /etc/nginx/conf.d/jenkins.conf
      state: touch
        
  - name: Configure Nginx as reverse proxy for Jenkins
    blockinfile:
      path: /etc/nginx/conf.d/jenkins.conf
      block: |
        server {
              listen 80;
              server_name 192.168.1.31;
              access_log /var/log/nginx/jenkins.access.log;

              location / {
                  proxy_pass http://192.168.1.31:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
               }

              location /userContent {
                root /var/lib/jenkins/;
                if ($query_string) {
                    expires max;
                  }
              }

            error_page 404 /404.html;
                location = /404.html {
                internal;
              }

            error_page 500 502 503 504 /50x.html;
               location = /50x.html {
               internal;
              }
          }
    notify: wait for nginx
  - name: Reboot the system
      become: true
      reboot:
        reboot_timeout: 3600
        msg: "Reboot initiated by Ansible"

